import { pgTable, text, real, jsonb, uuid, foreignKey, index } from "drizzle-orm/pg-core";
import { createdAt, id, updatedAt } from "./helpers";
import { searches } from "./searches";
import type {
  CandidateScore,
  CandidateSource,
  CandidateStatus,
  Classification,
  GttCriteria,
  LinkedInProfile,
  Resolution,
  ResidenceRegion,
  ExaPersonEntity,
  PersonaAttributes,
  Sector,
  TalentCategory,
  UkLinks,
} from "../../types";

export const candidates = pgTable(
  "candidates",
  {
    id,
    searchId: uuid(),
    category: text().$type<TalentCategory>().notNull(),
    sector: text().$type<Sector>().notNull(),
    subSector: text(),
    criteria: text().$type<GttCriteria>(),
    residenceRegion: text().$type<ResidenceRegion>(),
    nationality: text(),
    exaId: text(),
    source: text().$type<CandidateSource>().notNull().default("search"),
    profileUrl: text().unique(),
    name: text().notNull(),
    headline: text(),
    title: text(),
    organisation: text(),
    location: text(),
    country: text(),
    pictureUrl: text(),
    entity: jsonb().$type<ExaPersonEntity>(),
    highlights: text().array().notNull().default([]),
    notes: text(),
    linkedinProfile: jsonb().$type<LinkedInProfile>(),
    resolution: jsonb().$type<Resolution>(),
    profileText: text(),
    status: text().$type<CandidateStatus>().notNull().default("discovered"),
    error: text(),
    ukLinks: jsonb().$type<UkLinks>(),
    persona: jsonb().$type<PersonaAttributes>(),
    classification: jsonb().$type<Classification>(),
    score: jsonb().$type<CandidateScore>(),
    overallScore: real(),
    opennessScore: real(),
    ukLinkScore: real(),
    createdAt,
    updatedAt,
  },
  (table) => [
    foreignKey({
      columns: [table.searchId],
      foreignColumns: [searches.id],
      name: "candidates_search_id_fkey",
    }).onDelete("set null"),
    index("candidates_search_id_idx").on(table.searchId),
    index("candidates_overall_score_idx").on(table.overallScore),
  ],
);
