/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppShortlistRouteImport } from './routes/_app.shortlist'
import { Route as AppCandidatesCandidateIdRouteImport } from './routes/_app.candidates.$candidateId'
import { Route as AppSearchesIndexRouteImport } from './routes/_app.searches.index'
import { Route as AppSearchesSearchIdRouteImport } from './routes/_app.searches.$searchId'
import { Route as AppCandidatesCandidateIdIndexRouteImport } from './routes/_app.candidates.$candidateId.index'
import { Route as AppCandidatesCandidateIdInterviewRouteImport } from './routes/_app.candidates.$candidateId.interview'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShortlistRoute = AppShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesCandidateIdRoute =
  AppCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSearchesIndexRoute = AppSearchesIndexRouteImport.update({
  id: '/searches/',
  path: '/searches/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchesSearchIdRoute = AppSearchesSearchIdRouteImport.update({
  id: '/searches/$searchId',
  path: '/searches/$searchId',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesCandidateIdIndexRoute =
  AppCandidatesCandidateIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCandidatesCandidateIdRoute,
  } as any)
const AppCandidatesCandidateIdInterviewRoute =
  AppCandidatesCandidateIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AppCandidatesCandidateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/shortlist': typeof AppShortlistRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRouteWithChildren
  '/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/searches/': typeof AppSearchesIndexRoute
  '/candidates/$candidateId/interview': typeof AppCandidatesCandidateIdInterviewRoute
  '/candidates/$candidateId/': typeof AppCandidatesCandidateIdIndexRoute
}
export interface FileRoutesByTo {
  '/shortlist': typeof AppShortlistRoute
  '/': typeof AppIndexRoute
  '/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/searches': typeof AppSearchesIndexRoute
  '/candidates/$candidateId/interview': typeof AppCandidatesCandidateIdInterviewRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/shortlist': typeof AppShortlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/candidates/$candidateId': typeof AppCandidatesCandidateIdRouteWithChildren
  '/_app/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/_app/searches/': typeof AppSearchesIndexRoute
  '/_app/candidates/$candidateId/interview': typeof AppCandidatesCandidateIdInterviewRoute
  '/_app/candidates/$candidateId/': typeof AppCandidatesCandidateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shortlist'
    | '/candidates/$candidateId'
    | '/searches/$searchId'
    | '/searches/'
    | '/candidates/$candidateId/interview'
    | '/candidates/$candidateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/shortlist'
    | '/'
    | '/searches/$searchId'
    | '/searches'
    | '/candidates/$candidateId/interview'
    | '/candidates/$candidateId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/shortlist'
    | '/_app/'
    | '/_app/candidates/$candidateId'
    | '/_app/searches/$searchId'
    | '/_app/searches/'
    | '/_app/candidates/$candidateId/interview'
    | '/_app/candidates/$candidateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shortlist': {
      id: '/_app/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof AppShortlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$candidateId': {
      id: '/_app/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AppCandidatesCandidateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches/': {
      id: '/_app/searches/'
      path: '/searches'
      fullPath: '/searches/'
      preLoaderRoute: typeof AppSearchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches/$searchId': {
      id: '/_app/searches/$searchId'
      path: '/searches/$searchId'
      fullPath: '/searches/$searchId'
      preLoaderRoute: typeof AppSearchesSearchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$candidateId/': {
      id: '/_app/candidates/$candidateId/'
      path: '/'
      fullPath: '/candidates/$candidateId/'
      preLoaderRoute: typeof AppCandidatesCandidateIdIndexRouteImport
      parentRoute: typeof AppCandidatesCandidateIdRoute
    }
    '/_app/candidates/$candidateId/interview': {
      id: '/_app/candidates/$candidateId/interview'
      path: '/interview'
      fullPath: '/candidates/$candidateId/interview'
      preLoaderRoute: typeof AppCandidatesCandidateIdInterviewRouteImport
      parentRoute: typeof AppCandidatesCandidateIdRoute
    }
  }
}

interface AppCandidatesCandidateIdRouteChildren {
  AppCandidatesCandidateIdInterviewRoute: typeof AppCandidatesCandidateIdInterviewRoute
  AppCandidatesCandidateIdIndexRoute: typeof AppCandidatesCandidateIdIndexRoute
}

const AppCandidatesCandidateIdRouteChildren: AppCandidatesCandidateIdRouteChildren =
  {
    AppCandidatesCandidateIdInterviewRoute:
      AppCandidatesCandidateIdInterviewRoute,
    AppCandidatesCandidateIdIndexRoute: AppCandidatesCandidateIdIndexRoute,
  }

const AppCandidatesCandidateIdRouteWithChildren =
  AppCandidatesCandidateIdRoute._addFileChildren(
    AppCandidatesCandidateIdRouteChildren,
  )

interface AppRouteChildren {
  AppShortlistRoute: typeof AppShortlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCandidatesCandidateIdRoute: typeof AppCandidatesCandidateIdRouteWithChildren
  AppSearchesSearchIdRoute: typeof AppSearchesSearchIdRoute
  AppSearchesIndexRoute: typeof AppSearchesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShortlistRoute: AppShortlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppCandidatesCandidateIdRoute: AppCandidatesCandidateIdRouteWithChildren,
  AppSearchesSearchIdRoute: AppSearchesSearchIdRoute,
  AppSearchesIndexRoute: AppSearchesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
