/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCandidatesCandidateIdRouteImport } from './routes/_app.candidates.$candidateId'
import { Route as AppSearchesIndexRouteImport } from './routes/_app.searches.index'
import { Route as AppSearchesSearchIdRouteImport } from './routes/_app.searches.$searchId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesCandidateIdRoute =
  AppCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSearchesIndexRoute = AppSearchesIndexRouteImport.update({
  id: '/searches/',
  path: '/searches/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchesSearchIdRoute = AppSearchesSearchIdRouteImport.update({
  id: '/searches/$searchId',
  path: '/searches/$searchId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/searches/': typeof AppSearchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/searches': typeof AppSearchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/_app/searches/$searchId': typeof AppSearchesSearchIdRoute
  '/_app/searches/': typeof AppSearchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/candidates/$candidateId' | '/searches/$searchId' | '/searches/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidates/$candidateId' | '/searches/$searchId' | '/searches'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/candidates/$candidateId'
    | '/_app/searches/$searchId'
    | '/_app/searches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$candidateId': {
      id: '/_app/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AppCandidatesCandidateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches/': {
      id: '/_app/searches/'
      path: '/searches'
      fullPath: '/searches/'
      preLoaderRoute: typeof AppSearchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches/$searchId': {
      id: '/_app/searches/$searchId'
      path: '/searches/$searchId'
      fullPath: '/searches/$searchId'
      preLoaderRoute: typeof AppSearchesSearchIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCandidatesCandidateIdRoute: typeof AppCandidatesCandidateIdRoute
  AppSearchesSearchIdRoute: typeof AppSearchesSearchIdRoute
  AppSearchesIndexRoute: typeof AppSearchesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCandidatesCandidateIdRoute: AppCandidatesCandidateIdRoute,
  AppSearchesSearchIdRoute: AppSearchesSearchIdRoute,
  AppSearchesIndexRoute: AppSearchesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
